blueprint:
  name: One-way cover sync (controller → multiple followers)
  description: >
    Mirrors a controller cover to one or more follower covers. Controller moves → all
    followers mirror. Follower changes do NOT affect the controller. Mirrors position and
    (optionally) open/close. Uses modern "actions" syntax (2024.8+).
  domain: automation
  input:
    controller_cover:
      name: Controller cover
      description: The cover whose changes should be mirrored
      selector:
        entity:
          domain: cover
    follower_covers:
      name: Follower covers
      description: Select one or more covers that will follow the controller
      selector:
        entity:
          domain: cover
          multiple: true
    min_delta:
      name: Minimum position delta (%)
      description: >
        Only mirror position to a follower when the difference is at least this many percent.
        Use 0 to mirror every position change.
      default: 2
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: box
          unit_of_measurement: "%"
    mirror_open_close:
      name: Also mirror open/close commands
      description: >
        If enabled, when the controller opens/closes, all followers will open/close too.
        Helpful if your covers don’t report fine-grained position.
      default: true
      selector:
        boolean: {}

mode: restart

variables:
  ctrl: !input controller_cover
  followers: !input follower_covers
  min_delta: !input min_delta
  mirror_open_close: !input mirror_open_close

triggers:
  # Mirror position changes from controller → followers
  - trigger: state
    entity_id: !input controller_cover
    attribute: current_position

  # Optionally mirror open/close state from controller → followers
  - trigger: state
    entity_id: !input controller_cover
    to:
      - "open"
      - "opening"
      - "closed"
      - "closing"

conditions: []

actions:
  - choose:
      # === Position sync (preferred when controller exposes current_position) ===
      - conditions:
          - condition: template
            value_template: >
              {{ trigger is not
