blueprint:
  name: One-way cover position sync (controller → multiple followers)
  description: >
    Mirrors the controller cover's position (0–100%) to one or more follower covers.
    Only reacts to current_position changes; open/close state is ignored.
    Uses modern actions syntax (2024.8+).
  domain: automation
  input:
    controller_cover:
      name: Controller cover
      selector:
        entity:
          domain: cover
    follower_covers:
      name: Follower covers
      description: One or more covers that will follow the controller's position
      selector:
        entity:
          domain: cover
          multiple: true

mode: restart

variables:
  ctrl: !input controller_cover
  followers: !input follower_covers

trigger:
  - platform: state
    entity_id: !input controller_cover
    attribute: current_position

condition: []

action:
  - action: cover.set_cover_position
    target:
      entity_id: !input follower_covers
    data:
      position: "{{ trigger.to_state.attributes.current_position | int }}"
